// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://www.delineate.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.delineate.io/support",
            "email": "support@delineate.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "post": {
                "description": "Creates a new customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "summary": "Create Customer",
                "parameters": [
                    {
                        "description": "customer",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.Customer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Customer created"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "409": {
                        "description": "Customer exists"
                    },
                    "500": {
                        "description": "Internal error"
                    }
                }
            }
        },
        "/customer/{id}": {
            "get": {
                "description": "Returns a single customer",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get Customer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Customer returned",
                        "schema": {
                            "$ref": "#/definitions/routes.Customer"
                        }
                    },
                    "404": {
                        "description": "Customer not found"
                    },
                    "500": {
                        "description": "Internal error"
                    }
                }
            }
        },
        "/customers": {
            "get": {
                "description": "gets a list of all the customers",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get Customers",
                "responses": {
                    "200": {
                        "description": "Customers returned",
                        "schema": {
                            "$ref": "#/definitions/routes.Customers"
                        }
                    },
                    "500": {
                        "description": "Internal error"
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "checks the health of the service",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "healthy"
                    }
                }
            }
        }
    },
    "definitions": {
        "routes.Customer": {
            "type": "object",
            "required": [
                "dob",
                "forename",
                "surname"
            ],
            "properties": {
                "dob": {
                    "type": "string"
                },
                "forename": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "routes.Customers": {
            "type": "object",
            "properties": {
                "customers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.Customer"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:1102",
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "Customer Service",
	Description: "Service for managing customers",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
